name: Prepare environment

inputs:
  'python-version':
    required: false
    default: '3.9'
  'poetry-version':
    required: false
    default: '1.2.2'

runs:
  using: "composite"

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry ${{ inputs.poetry-version }}
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Define a cache for the virtual environment
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Create the in-project virtualenv if it doesn't exist
      shell: bash
      run: test -d .venv || python -m venv .venv

    - name: Install dependencies using Poetry
      shell: bash
      run: |
        poetry --version
        poetry install --no-ansi --no-interaction
        poetry show
